#!/usr/bin/env python
"""Generate Kaggle launcher notebooks in dist/kaggle/ from the SAME package + configs.

    python scripts/export_kaggle.py

Each launcher embeds a base64 zip of src/yolov11sdi + configs + pyproject, so
Kaggle runs exactly the local code and config (same config hashes, same tags).
/kaggle/working is only a runtime cache; persistent outputs go to Camber.
Re-export after any code/config change.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import _bootstrap  # noqa: F401

from yolov11sdi.nbgen import bundle_project, check_compiles, code, md, notebook, write_notebook

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "dist" / "kaggle"

STAGE_DEPS = "pyyaml pandas pillow numpy imagehash opencv-python-headless fiftyone==1.22.1 gdown huggingface_hub tqdm"
TRAIN_DEPS = "pyyaml pandas pillow numpy ultralytics==8.4.172"


def setup_cells(bundle: str, digest: str, deps: str) -> list[dict]:
    return [
        code(f"!pip install -q {deps}"),
        code(f'''\
        # Unpack the embedded project bundle (generated by scripts/export_kaggle.py, sha256 {digest[:16]}).
        import base64, io, os, sys, zipfile
        from pathlib import Path
        BUNDLE = "{bundle}"
        SRC_ROOT = Path("/kaggle/working/yolov11sdi_src")
        zipfile.ZipFile(io.BytesIO(base64.b64decode(BUNDLE))).extractall(SRC_ROOT)
        sys.path.insert(0, str(SRC_ROOT / "src"))
        os.environ["YOLOV11SDI_PROJECT_ROOT"] = str(SRC_ROOT)
        os.environ["YOLOV11SDI_ENV"] = "kaggle"
        print("bundle", "{digest[:16]}", "->", SRC_ROOT)'''),
        code('''\
        # Camber CLI + key from Kaggle Secrets (never printed, never stored in files).
        import shutil, subprocess
        from yolov11sdi.environment import load_camber_api_key
        if shutil.which("camber") is None and not (Path.home() / ".camber/bin/camber").exists():
            subprocess.check_call("curl -sL https://cli.cambercloud.com/install-v2.sh | bash", shell=True)
        os.environ["PATH"] = f"{Path.home()}/.camber/bin:{Path.home()}/.local/bin:" + os.environ.get("PATH", "")
        assert load_camber_api_key(), "Enable the Kaggle Secret CAMBER_API_KEY for this notebook."
        from yolov11sdi import pipeline
        from yolov11sdi.paths import ProjectPaths
        paths = ProjectPaths.detect().ensure()
        print("home:", paths.home)'''),
    ]


def launchers(bundle: str, digest: str) -> dict[str, list[dict]]:
    return {
        "KAGGLE_V6P5_EXTERNAL_STAGE.ipynb": [
            md("""
            # V6.5 external stage (Kaggle launcher, generated)
            Runs parent → openimages → mpcd → power_equipment → synthetic → dedup → external_freeze with the
            project package. Disk-safe: parent archives streamed then deleted; Open Images detections-only.
            Outputs are uploaded to `.../datasets/v6p5_external_stage/v6p5_ext_<tag>/` + fixed direct archives.
            Restart-safe: rerun all; finished stages in this session are reused.
            """),
            *setup_cells(bundle, digest, STAGE_DEPS),
            code('''\
            for s in ["parent", "openimages", "mpcd", "power_equipment", "synthetic", "dedup", "external_freeze"]:
                print(pipeline.run_stage(s))'''),
            code('print(pipeline.StateStore(paths.state).load("external_freeze").summary)'),
        ],
        "KAGGLE_V6P5_COMPOSE_QA.ipynb": [
            md("""
            # V6.5 compose QA (Kaggle launcher, generated)
            Selects the single `v6p5_ext_*` on Camber (or `compose.stage_tag`), applies the human decisions
            and produces `v6p5_compose_<tag>`. Upload your filled decisions CSV as a Kaggle dataset and set
            `DECISIONS_CSV` below. Stops with `needs_review` while TRAIN candidates are pending.
            """),
            *setup_cells(bundle, digest, STAGE_DEPS),
            code('''\
            DECISIONS_CSV = None   # e.g. "/kaggle/input/v65-review/v6p5_review_decisions.csv"
            if DECISIONS_CSV:
                dst = paths.resolve("artifacts/qa/v6p5_review_decisions.csv")
                dst.parent.mkdir(parents=True, exist_ok=True); shutil.copyfile(DECISIONS_CSV, dst)
            outcome = pipeline.run_stage("compose")
            print(outcome)'''),
            code('''\
            # Download this file from the Kaggle output panel to review locally if needed.
            print(paths.resolve("artifacts/qa/v6p5_review_decisions.csv"))'''),
        ],
        "KAGGLE_V6P5_YOLO11N_ABLATION.ipynb": [
            md("""
            # V6.5 YOLO11n@640 data ablation (Kaggle GPU launcher, generated)
            NOT the final V6.5-vs-V6.4 benchmark. Auto-discovers exactly one `v6p5_compose_*` (or set
            `training.compose_tag`). Checkpoints sync to Camber every `sync_every_epochs`; after a Kaggle
            restart, rerun all — `last.pt` is restored from Camber and training resumes.
            """),
            *setup_cells(bundle, digest, TRAIN_DEPS),
            code('''\
            outcome = pipeline.run_stage("yolo11n_ablation")
            print(outcome)'''),
            code('print(pipeline.run_stage("evaluate"))'),
        ],
    }


def main() -> None:
    bundle = bundle_project(ROOT)
    digest = hashlib.sha256(bundle.encode()).hexdigest()
    for name, cells in launchers(bundle, digest).items():
        nb = notebook(cells, kaggle=True)
        check_compiles(nb, name)
        p = write_notebook(OUT / name, nb)
        print(f"{p.relative_to(ROOT)}  ({p.stat().st_size / 1024:.0f} KB, bundle {digest[:12]})")


if __name__ == "__main__":
    main()
